tasks:
  - init: |
      curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | sudo bash
      sudo chown -R gitpod:gitpod LanguageTool-5.6-stable/
      cd LanguageTool-5.6-stable/
